# Generated by Django 5.1.2 on 2024-11-10 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='AuthorModel',
        ),
        migrations.RenameModel(
            old_name='Book',
            new_name='BookModel',
        ),
        migrations.RenameModel(
            old_name='Librarian',
            new_name='LibrarianModel',
        ),
        migrations.RenameModel(
            old_name='Library',
            new_name='LibraryModel',
        ),
    ]
