# Generated by Django 5.1.2 on 2024-11-10 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_rename_author_authormodel_rename_book_bookmodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorModel',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='BookModel',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='LibrarianModel',
            new_name='Librarian',
        ),
        migrations.RenameModel(
            old_name='LibraryModel',
            new_name='Library',
        ),
    ]
